### ISSUE TITLE
Todo List error on KDE Plasma 5.10.5

### ISSUE THREAD

**Issue by Warmuser** [Zren/plasma-applets#100]
Hello again, I want report these issue for the Todo List applet. 

Error loading QML file: file:///home/wmv/.local/share/plasma/plasmoids/com.github.zren.todolist/contents/ui/main.qml:10:5: Type NoteItem unavailable
file:///home/wmv/.local/share/plasma/plasmoids/com.github.zren.todolist/contents/ui/NoteItem.qml:11:1: module "org.kde.plasma.private.notes" is not installed

I run these applet on KDE 5.10.5.

**Comment by Zren** [comment]
> https://store.kde.org/p/1152230/

> **Requires the kdeplasma-addons package** (sudo apt install kdeplasma-addons) since we use the sticky note widget's code to save to file.

**Comment by Warmuser** [comment]
Wow, thank you so much! :)
