### ISSUE TITLE
Google Calendar shows nothing and refuses to logout

### ISSUE THREAD

**Issue by Tromzy** [Zren/plasma-applets#101]
I configured Google Calendar but I have two Google accounts and I logged to the incorrect one, so I tried to logout : when I click the "logout" button, it shows the login code agin, but actually if I leave and come back, I'm still logged in, so I cannot switch to my other Google account.

**Comment by Zren** [comment]
Uhg, thanks for reporting. Will be fixed in v49.

**Comment by Zren** [comment]
Can't believe I didn't publish v49. I'm so sorry. I just released v50 which includes the fix.
