### ISSUE TITLE
Translated to Portuguese Brazil pt_BR

### ISSUE THREAD

**Issue by clayzanfolin** [Zren/plasma-applets#109]
Hello, I translated to Portuguese Brazil for me. if they want to use it, there it is to help other Brazilians or Portuguese.

**Comment by Zren** [comment]
Did you mean to make a pull request?

If you're not sure how to do so, just save the `pt_BR.po` as a txt file (`pt_BR.txt`) and attach it to your comment.

Eg: [fr.po.txt](https://github.com/Zren/plasma-applets/files/1420314/fr.po.txt)

Which widget did you translate btw?

**Comment by clayzanfolin** [comment]
I'm learning GitHub, so as not to harm the project I'll attach the file.
[pt_BR.po.txt](https://github.com/Zren/plasma-applets/files/1423748/pt_BR.po.txt)

Thank you!

**Comment by Zren** [comment]
If you're willing to learn, you can try submitting a Pull Request via the website here:

https://github.com/Zren/plasma-applets/new/master?new_filename=org.kde.plasma.eventcalendar/package/locale/pt_BR.po&filename=pt_BR.po

Otherwise I'll merge it myself in a few hours.
