### ISSUE TITLE
fixed ukrainian translate

### ISSUE THREAD

**Issue by cappelikan** [Zren/plasma-applets#112]
[ukrainian.txt](https://github.com/Zren/plasma-applets/files/1432241/ukrainian.txt)

**Comment by Zren** [comment]
I'd already fixed some of the issues in this commit: https://github.com/Zren/plasma-applets/commit/3224d197cfe3114b5974120710b8f0a0f3518749

So I manually merged your updated translations in this commit: https://github.com/Zren/plasma-applets/commit/e72eee5cf724a3ac7a075183bba8283410c0eeef

What it looks like now: https://github.com/Zren/plasma-applets/blob/master/org.kde.plasma.eventcalendar/package/locale/uk.po
