### ISSUE TITLE
Layout issue when size is reduced

### ISSUE THREAD

**Issue by FabriceSalvaire** [Zren/plasma-applets#116]
I would like to make the widget smaller, but

* _nov_ in calendar are misplaced (always)
* timer icons are not layout correctly

![event-calendar](https://user-images.githubusercontent.com/2358471/32701334-c5be36e8-c7d3-11e7-863b-eb96e712bb75.png)

Could look in qml code when I will have time ...

**Comment by FabriceSalvaire** [comment]
nov misplacing is due to unconfigured wheather

**Comment by Zren** [comment]
When I get around to releasing v51:

* Fixed horizontal overflow in "weather not configured". I think it might still overflow vertically if the translated text is too long... meh.

![](https://i.imgur.com/qG80NnK.png)

* Fixed overflow in timer preset buttons. It will now reveal a button only if there's enough space. You can still the hidden presets by right clicking the timer "start/pause" button.
* Dynamically hide the "Repeat/Sound" toggle button labels if there isn't enough space.

I toyed around with moving the toggle buttons to the left of the pause button, but it doesn't look great when the labels are visible.

![](https://i.imgur.com/uBOcKoe.png)
![](https://i.imgur.com/3AckASB.png)

* I don't think I fixed the "nov. 20" overflow. I've had it happen to me in the past though. I also know that show/hiding the "weather text" doesn't adjust the "row height" unless you refresh. I'll need to look into that.
