### ISSUE TITLE
[Tiled Menu] How to change background of tiles?

### ISSUE THREAD

**Issue by redfox12317** [Zren/plasma-applets#120]
Hi,

I just recently ran into your awesome plasmoid and I have to say I love it. I saw that it said you could easily change the background image of a tile. It looks really cool in the review pictures you provided on kde.org. I especially like the Steam background you added. I cannot seem to find out how to get that advanced edit tile option where it shows where to choose the background image, size options, web url, label, etc. I'm probably missing something really easy here but I have no idea. I've tried right clicking the tile, I've gone into tiled menu settings etc. I'm stuck.

**Comment by Zren** [comment]
The feature was added in v15, so it's only in the Plasma 5.9+ version.

Right Click Tile > Edit Tile > Background Color

![](https://i.imgur.com/RkAMMc3.png)
