### ISSUE TITLE
[EventCalendar] Crash in latte dock

### ISSUE THREAD

**Issue by forkbomb9** [Zren/plasma-applets#121]
I have a crash at login when Event Calendar is in the top dock.

My system specs are:
![system specs](https://user-images.githubusercontent.com/33267474/34066467-ffe96c8e-e1dc-11e7-8724-3a5c7e5fd7d3.png)

Tell my tell me what information you need, I no have idea :(

**Comment by Zren** [comment]
Only at login? Or does it crash if you try to run plasmashell manually via the terminal too?

What version of Qt?

I assume Plasma 5.11.4

Does plasmashell crash if you try adding it to an empty Plasma panel?

**Comment by namkhaib** [comment]
@Zren, it's only at login.
Qt version: 5.9.3
Plasma 5.11.4, yes
And plasma shell don't crash if I add it to a empty Plasma panel

**Comment by namkhaib** [comment]
@Zren, the crash it's not in plasmashell,  it's in <a href=https://github.com/psifidotos/Latte-Dock/issues/800>LatteDock</a> plasmoid. EventCalendar crashes Latte

**Comment by Zren** [comment]
> Only at login? Or does it crash if you try to run ~~plasmashell~~ `latte-dock` manually via the terminal too?

Woops meant to ask if it crashes when you manually run `latte-dock`.

**Comment by namkhaib** [comment]
@Zren, not don't crashes

**Comment by namkhaib** [comment]
Also,  I don't want to replace EventCalendar, it's a very good Plasmoid 🥇

**Comment by namkhaib** [comment]
Any idea of what's the cause of this? If i can help anyway, tell me

**Comment by Zren** [comment]
Ah, there was [this bug report for Latte Dock](https://github.com/psifidotos/Latte-Dock/issues/799).

Have you tried removing event calendar, then relogging? Does it still crash?

**Comment by Zren** [comment]
>  And Latte don't crash if I remove EventCalendar

Oh woops missed that. Uhg.
