### ISSUE TITLE
[VolumeMixer] Changing the volume with the mousewheel while hovering over applet does not work anymore

### ISSUE THREAD

**Issue by joseffilzmaier** [Zren/plasma-applets#123]
Hello!
Since the latest update (Version 21) i cannot use the mousewheel to change the volume of the default output when hovering over the system tray icon). I am on Arch Linux using the AUR version of this great applet.

It would be nice if you could fix this so that i can change the volume with my mouse wheel again.

**Comment by Zren** [comment]
Oh woops. I totally forgot to reimplement that, Sorry. My mouse wheel broke and have been lazy about replacing it so the middle mouse button completely skipped my mind. I'll see about pushing out v22 tomorrowish.

**Comment by Zren** [comment]
v22 is released
