### ISSUE TITLE
[Event Calendar] Not syncing new/modified events

### ISSUE THREAD

**Issue by Roboron3042** [Zren/plasma-applets#126]
I've been using Event Calendar for a while, but recently i noticed that it is not showing me new events, or events i have modified. If i disconnect/reconnect my Google Account, it keeps showing my "old" events (and i mean events i added long time ago, not events from the past), but not new or modified events. Has changed how Google Calendar works recently and that's the reason which it doesn't work? Or I am the only one having this problem?

**Comment by Zren** [comment]
Latest version (v51)?

* How many calendars do you have?
* Does it only affect the current month, or does it also affect next month?
* How many events do you have in the specific month for each calendar? 2 events per day?

It's definitely still working for me, though when I clink an event to edit in the browser, it's now using the Material Design look. It's also showing the event in the Month View now, so I'm going to need to change the link to the "full editor" (`https://calendar.google.com/calendar/r/eventedit/{{eventId}}`).

**Comment by Roboron3042** [comment]
This morning I was re-arranging the calendar and I "accidentally" fixed the problem. And I discovered what was causing it. Apparently, I can't have more than 11 events per day or the Event Calendar won't show the newest. Yesterday I had 12 events or more per day (it depends of the day, but most of them are daily, others are weekly, and only some are uniques), today I have an average of 7 per day and no more than 10 and so is working perfectly. 
However, i tried to replicate the problem creating fake events and I only ended in the same situation if those fake events were daily, but not if they were unique. So it seems that there is a limit with daily events (idk if it sums with weekly events or not), that doesn't exist for unique events.

As for your questions:

> Latest version (v51)?

Of course

> How many calendars do you have?

Synced, two. Contact Calendar and my personal Calendar.

> Does it only affect the current month, or does it also affect next month?

It affects every month, every day indeed, not only those with less events than this supposed limit allow.

> How many events do you have in the specific month for each calendar? 2 events per day?

Answered already.

**Comment by Zren** [comment]
Woops. I totally didn't get around to fetching paginated events.

There's a "second page" of events I need to fetch when there's >250 events in a calendar for a specific month.

* https://developers.google.com/google-apps/calendar/v3/reference/events/list
* `nextPageToken`

**Comment by Zren** [comment]
Sorry for the delay, v52 should fix this.
