### ISSUE TITLE
[EventCalendar] Some incorrect date

### ISSUE THREAD

**Issue by Aetf** [Zren/plasma-applets#133]
After the recent upgrade, I found the highlight of today is offset by 1 day
![image](https://user-images.githubusercontent.com/1519759/41617132-b1eeda9a-73cd-11e8-8f1e-72a063e55d7e.png)
In the screenshot, today's date is June 19, 2018, but the calendar shows and highlights June 18. In the left column, June 19 is correctly highlighted, but June 18 is shown as the first item.

Another probably related issue: when clicking on a month, the previous month is selected
![output](https://user-images.githubusercontent.com/1519759/41617587-e133ac62-73ce-11e8-80d4-275a4c22370c.gif)

**Comment by Zren** [comment]
Closing as duplicate. This bug should be fixed when KDE Frameworks 5.48 is released (July 14th).
