### ISSUE TITLE
Could you please make plasma-hud (your mate-hud fork) issue friendly ?

### ISSUE THREAD

**Issue by kupiqu** [Zren/plasma-applets#135]
Sorry to open an issue where it is not due, but couldn't find a better way to request making it able to open issues for your plasma-hud fork of mate-hud.

I was about to open an issue there [to, in addition to congratulate you for such a nice work, ask about the possibility to change the look and feel of the hud; would like to change colors, but more importantly the font size which appears way too small in my system], when I realized I was not able to.

Thanks and sorry to report where it is not proper.

**Comment by Zren** [comment]
Sure https://github.com/Zren/plasma-hud/issues
