### ISSUE TITLE
Wasted space / different colour on popup

### ISSUE THREAD

**Issue by rnc** [Zren/plasma-applets#2]
On my calendar popup I can see some wasted space (and its in a different colour) on the left hand side. 

![calendarpopup](https://cloud.githubusercontent.com/assets/1169793/14014322/be9a4c46-f1a9-11e5-9ed7-59a8a4979ead.jpg)

I am using Fedora 23 with KDE 5.5.5.

**Comment by Zren** [comment]
This is a placeholder for the 24h forecast graph. I removed the solid color since it's really gaudy. I just didn't want people suggesting the agenda to take up that space since it'd be a pain to revert I think.

I also added the ability to hide it altogether along with the timer widget. So closing.
