### ISSUE TITLE
Repeated event

### ISSUE THREAD

**Issue by vmorenomarin** [Zren/plasma-applets#22]
I will use an international date,  the _International Workers' Day_,  to explain the bug:

![bug](https://cloud.githubusercontent.com/assets/13444664/14754516/88f1d8fc-08a1-11e6-9324-d6b5cdf58ea2.png)

As you see in the picture, there are two _International Workers' Day_ in the calendar, but that date is only the 1st of May. Nevertheless, in the left list they are not repeated. This bug is present for other dates in my agenda.

**Comment by Zren** [comment]
Ah, I fixed this yesterday. Probably should release a new build with it. It should be released in v29 by the time you read this.
