### ISSUE TITLE
Timer notification sound

### ISSUE THREAD

**Issue by vmorenomarin** [Zren/plasma-applets#23]
Hi.

Is there a way to add a sound to the notification when timer has ended?

Thanks.

**Comment by Zren** [comment]
So, KDE doesn't completely follow the [notification spec](https://developer.gnome.org/notification-spec/) (yet?) which does specify sounds (which is what I experimented the first time I went looking).

* https://github.com/KDE/plasma-workspace/blob/master/dataengines/notifications/notifications.operations#L16
* https://github.com/KDE/plasma-workspace/blob/master/dataengines/notifications/notificationaction.cpp
* https://github.com/KDE/plasma-workspace/blob/master/dataengines/notifications/notificationsengine.cpp#L394

I could however probably play  a [SoundEffect](http://doc.qt.io/qt-5/qml-qtmultimedia-soundeffect.html) with QML with a filename entered in the config.

Having the sound file managed in the SystemSettings > Notifications would be nice, but seems [ridiculously complicated](http://api.kde.org/frameworks-api/frameworks5-apidocs/knotifications/html/classKNotification.html) for a pure QML appplet.

```qml
import QtMultimedia 5.6

    function createNotification() {
        //...
        playSound.play()
    }


    SoundEffect {
        id: playSound
        source: "file:///usr/share/sounds/Oxygen-Sys-Warning.ogg"
        // source: "Oxygen-Sys-Warning.ogg"
    }
```

Doesn't seem to work `QSoundEffect(pulseaudio): Error decoding source`. Permission error mayhaps? Nyways, I'll look eventually.

**Comment by Zren** [comment]
Uhg, looks like I was using the wrong class. SoundEffect is used for playing uncompressed file types like wav. I need to use [Audio](http://doc.qt.io/qt-5/qml-qtmultimedia-audio.html) class. Now to pick a good default sound (I'll probably need a file chooser in the settings).

```qml
import QtQuick 2.0
import QtMultimedia 5.6

Item {
    Audio {
        id: playSound
        source: "/usr/share/sounds/freedesktop/stereo/complete.oga"
        source: "complete"
    }
    Component.onCompleted: {
        playSound.play()
    }
}
```

**Comment by Zren** [comment]
Added in v30.

**Comment by vmorenomarin** [comment]
Thansk a lot!!!
