### ISSUE TITLE
Provide ability to customise display

### ISSUE THREAD

**Issue by rnc** [Zren/plasma-applets#3]
e.g. display the date as well as time

**Comment by Welsing** [comment]
And seconds!

**Comment by Zren** [comment]
Just added a datetime format field with a preview + link to format documentation.

* Line 1: `MMM d - hh:mm:ss ap` Mar 24 09:45:39 pm

Eventually it should look like:
* Font: `dropdown`
* Line 1: `hh:mm` 09:45
* [x] Bold `Arial`
* [x] Line 2: `yyyy-MM-dd` 2016-03-24
* [ ] Bold

**Comment by Zren** [comment]
Added optional second line.

![](http://i.imgur.com/6S2BfIz.png)

Debating force the second line if the panel height is too high, since just 1 line will expand really wide.

Anything else other than being able to bold a line in the clock?

**Comment by Zren** [comment]
Hmmm, just noticed digitalclock has the time larger than the date. I probably should provide a slider to configure the height.

**Comment by Zren** [comment]
Just added font selection + boldness for the next version. Don't _really_ want to add italics unless someone requests it. Here's the final look of the clock config. It might get moved to it's own tab someday, but it's fine in general for now.

![](https://i.imgur.com/wWX3GIy.png)

Going to close this as it's feature complete with digitalclock.
