### ISSUE TITLE
Event Calendar: Improve weather configuration by pointing out full city list

### ISSUE THREAD

**Issue by AndydeCleyre** [Zren/plasma-applets#31]
Hi,

The event calendar is great, but openweathermap can be a nightmare to cooperate with, particularly in locating the correct city code. Some users might appreciate a link to the full city list as searchable text in a webpage: http://openweathermap.org/help/city_list.txt

This list could also be the source for an in-app search, but simply directing the user to it would be an improvement on its own.

**Comment by Zren** [comment]
This good? https://streamable.com/qcir

**Comment by AndydeCleyre** [comment]
Looks great!
