### ISSUE TITLE
event callendar Date will not advance

### ISSUE THREAD

**Issue by JPRuehmann** [Zren/plasma-applets#41]
Hello
Is there a way to make the Date advance without restart?
thanks
I am using Kubuntu 16.04 LTE and Version 36

**Comment by Zren** [comment]
Which date? The one in the clock? The highlighted date in the agenda?

**Comment by JPRuehmann** [comment]
both, the only time thats been updated is the timeline for the Weather.

**Comment by Zren** [comment]
https://streamable.com/kjpc

It changed for me.

**Comment by JPRuehmann** [comment]
![event callendar problem](https://cloud.githubusercontent.com/assets/4321829/19019400/31619b3e-8887-11e6-9166-775c2d1d2489.png)

Taken today 02.10.2016

Thanks,

**Comment by Zren** [comment]
Ooooh, You mean the Sept 27 in the calendar and the current date highlight also in the calendar. Thought you meant in the agenda.

**Comment by JPRuehmann** [comment]
The agenda is stuck to as you can see.

Thanks,

**Comment by JPRuehmann** [comment]
will there a resolution in the future?

**Comment by JPRuehmann** [comment]
It is unusable this way.

**Comment by Zren** [comment]
This should be fixed in v39. Sorry it took so long.

**Comment by JPRuehmann** [comment]
Works like a Charm, Thanks.
