### ISSUE TITLE
Wether not working anymore

### ISSUE THREAD

**Issue by JPRuehmann** [Zren/plasma-applets#42]
Hello
Since the Update to Version 37 Weather is not working anymore.
the Plasmoid says that it is not configured.
and the Configuration say that qtquick.layouts 1.3 is not installed.
I am using Kubuntu 16.04 LTS
How can I make it work again?
Thanks

**Comment by Zren** [comment]
Thanks for the report. I must have copy pasted the imports for the new dialogs. It doesn't need 1.3 (1.2 works) though it seems `Layout.fillHeight` doesn't work well in 16.04 (not sure about 16.10) so I'll have to set a fixed height for the dialog's table.

This'll be in v38 released sometime tonight.
