### ISSUE TITLE
Callendars not configurable (selectable and Collors) anymore

### ISSUE THREAD

**Issue by JPRuehmann** [Zren/plasma-applets#43]
Hello
since the Update to Version 37 I can´t select the showed Callendars anymore and the Events will not shown in the respective Collors anymore.
Thanks,

**Comment by Zren** [comment]
* Does hitting refresh, then opening up the GCal page work?

**Comment by JPRuehmann** [comment]
this helped, thanks.
but the advancing still not working even via the go to today Button.
Thanks,
