### ISSUE TITLE
[eventcalendar] Show agenda under month

### ISSUE THREAD

**Issue by vmorenomarin** [Zren/plasma-applets#47]
Recently I did configure my Event Calender in column mode. Excellent option. I thought that could appears an option to display the agenda under the month.

This widget is of my favorites. Thanks for the development.

**Comment by Zren** [comment]
Where should the meteogram and timer widgets be placed? Up top? Bottom?

**Comment by vmorenomarin** [comment]
Mmmm, I think that I suggested this feature based on my setting: I do not use timer and meteogram. Maybe, would be interesting that the user can choise the arrangement of the elements.

**Comment by matty-r** [comment]
@Zren This could be closed now I imagine.
