### ISSUE TITLE
A request for showing time from another timezone in the mouse over popup (tool tip) on the event calendar widget

### ISSUE THREAD

**Issue by raghukamath** [Zren/plasma-applets#49]
This is a feature request for showing time from other timezones chosen by the user in the tool tip of the event calendar. I searched for it but couldn't find a way to set it. It would be great help for people who want to check time of other timezones too.

**Comment by AdamEdry** [comment]
I want to add myself to this feature request. It's the only thing I'm missing from the digital clock widget that comes with KDE.

Great job on this widget! I love it

**Comment by Zren** [comment]
Added this since I had to fix a bug with Qt 5.9. It's in v48.
