### ISSUE TITLE
crashes with plasma 5.6 / Qt 5.6

### ISSUE THREAD

**Issue by ahjolinna** [Zren/plasma-applets#5]
I'm using chakraOS with plasma5.6 + Qt5.6 and everytime I try to open this calender my plasma panel crashes, here is my error output: 
```
trying to show an empty dialog
[New Thread 0x7ffefeafb700 (LWP 6535)]
[New Thread 0x7ffefdffa700 (LWP 6541)]
QQmlComponent: Component is not ready
[New Thread 0x7ffefcf26700 (LWP 6542)]
qml: onMonthViewDateChanged Fri Mar 25 00:00:00 2016 GMT+0200
qml: onSeletedDateChanged Fri Mar 25 00:00:00 2016 GMT+0200

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff540531b in QQmlIncubator::clear() () from /usr/lib/libQt5Qml.so.5

```
so qt5-declarative is the problem
and the google config did work just fine for me, it didn't crash for me

**Comment by Zren** [comment]
Yeah, I've no idea how to fix this.

> so qt5-declarative is the problem

http://doc.qt.io/qt-5/qtquick-porting-qt5.html#c-code

Don't recognize any of those classes.

Does the popup appear at all? Or does it crash before even displaying anything?

**Comment by ahjolinna** [comment]
plasma crashes immediately when I try to open it, I didn't see any "popup before that

**Comment by Zren** [comment]
I just tried the [22-Mar-2016 Kubuntu CI live cd](http://files.kde.org/snapshots/) with KDE Plasma 5.6.0, Frameworks 5.21.0, and Qt 5.5.1, and it works fine. So it seems to be the Qt version.

**Comment by XavierCLL** [comment]
I confirm the crash, using Archlinux plasma 5.6.1 and Qt 5.6

http://pastebin.com/ApW9YcV6

**Comment by ahjolinna** [comment]
@Zren: if you don't know how to fix it you can always ask help from [Qt's IRC channel's](https://wiki.qt.io/Online_Communities#IRC_channels) or/& [KDE](https://userbase.kde.org/IRC_Channels#Community.2FSupport)

**Comment by Zren** [comment]
Managed to get a livecd  with kde 5.6 and qt 5.6 setup in virtualbox today. Through a long process of elimination of commenting out stuff, I found a line that breaks.

[`MonthView { today: new Date() }`](https://github.com/Zren/plasma-applets/blob/master/org.kde.plasma.eventcalendar/package/contents/ui/PopupView.qml#L202)

I think I'll try changing that to `Component.onComplete: { today = new Date(); }` but I really need to figure out why the hell that breaks.

**Comment by Zren** [comment]
Does the new version (v23) work for you guys?

**Comment by XavierCLL** [comment]
With this version fixed for me, Thanks @Zren !

**Comment by ahjolinna** [comment]
nope, it does still crash for me on chakraOS (testing repo): uses plasma5.6.1, kf5.20, kde-apps 16.04 beta (kde-staging repos)

**Comment by ahjolinna** [comment]
I now wonder if this is correct? ![screenshot_20160405_193250](https://cloud.githubusercontent.com/assets/6993072/14289884/79d86b68-fb65-11e5-9e83-904ec796e373.png)
if not I will do a new bug report about it

**Comment by Zren** [comment]
Yes that screenshot looks correct. You need to set your city in the config to get weather, and sign into gcal there too for events.
