### ISSUE TITLE
TiledMenu does not work with git master (Plasma 5.9)

### ISSUE THREAD

**Issue by tittiatcoke** [Zren/plasma-applets#52]
As indicated also on the comments in store.kde.org, the TiledMenu does not work with the changes for Plasma 5.9.  e.g. showAllSubtree has now been changed into showAllApps.  

I made the above change locally and now the plasmoid starts, however the application menu is not displayed (Only recently used applications) and somehow most of the menu buttons on the left seems non-functional. 

Would be great to have this also for Plasma 5.9 in a way that you can maintain compatibility with the older Plasma versions.

**Comment by Zren** [comment]
Application Dashboard > All Applications doesn't work in neon-unstable either.

**Comment by Zren** [comment]
Bug is fixed upstream, I've yet to test to make sure it works though.

https://bugs.kde.org/show_bug.cgi?id=374375

**Comment by tittiatcoke** [comment]
Issue with the population of the menu has been resolved. I have now all applications in the menu visible. 

Only issue remaining is the switch from "showAllSubtree to showAllApps".

**Comment by Zren** [comment]
I tried setting the property dynamically earlier like so:

	Component.onCompleted: {
		if (typeof showAllSubTree !== "undefined") {
			showAllSubtree = true
		} else {
			showAllApps = true
		}
	}

But it was too slow. I think it tried loading the apps twice. So I'll be upping the plasma requirements closer to the [release of plasma 5.9 on Jan 31](https://community.kde.org/Schedules/Plasma_5).

**Comment by Zren** [comment]
Since the beta was just released today, I might as well bump it now. v12 is now on the store with this fix so closing.
