### ISSUE TITLE
time font size on vertical panel too large

### ISSUE THREAD

**Issue by gmoutso** [Zren/plasma-applets#6]
this is not the case with the default time+calendar. nice idea of plasmoid btw
![screen](https://cloud.githubusercontent.com/assets/2195071/14230277/ed895694-f958-11e5-833d-fdcf4b481feb.png)
in the screenshot, the plasmoid is the last one down.

**Comment by Zren** [comment]
![](https://i.imgur.com/mHxCNjk.png)

It's not nearly as compact as digitalclock, but ah well. Height is hardcoded at 24 or 48px for now.
