### ISSUE TITLE
Feature request: Allow changing order of date format

### ISSUE THREAD

**Issue by MattMcHackit** [Zren/plasma-applets#61]
In some parts of the world, the date is usually written as [Day of month] [Month], [Year] (e.g. 5 February, 2017), rather than [Month] [Day of month], [Year]. Would it be possible to allow this arrangement on the calendar title?

**Comment by Zren** [comment]
I think I'd need to parse the order, as I don't see a way to show just the day+month+year with the locale functions.

* http://doc.qt.io/qt-5/qt.html#DateFormat-enum
* `Qt.formatDate(today, Qt.DefaultLocaleShortDate)` == `2017-02-05`
* `Qt.formatDate(today, Qt.DefaultLocaleLongDate)` == `Sunday, Febuary 5, 2017`
* `today.toLocaleDateString()` == `Sunday, Febuary 5, 2017`
* http://doc.qt.io/qt-5/qml-qtqml-date.html#fromLocaleString-method
* http://doc.qt.io/qt-5/qml-qtqml-locale.html

I'll need to think on it.

**Comment by MattMcHackit** [comment]
Cool :-) thank you! Love your work!

**Comment by matty-r** [comment]
This can be closed and ticked off the issue list.
