### ISSUE TITLE
[Tiled menu] some ideas

### ISSUE THREAD

**Issue by omega3** [Zren/plasma-applets#67]
This is how it looks on my desktop
http://imgur.com/a/fcB90
It is Maia Transparent theme.

1. Would be grate to be able to change font colour.
2. Notice how a- two row application title in menu "Ośrodek informacji" goes below icon frame. 
3. See how some icons in menu are not fully visible. I think it would be grate if menu could be scalable to fit all favourable (something similar to Windows 10 would be great)
4. Sorting alphabetically and by categories is great but I think having option to choose also a classic view like in kickoff menu would be great.

**Comment by Zren** [comment]
1. The poor white on barely visible background is an issue for your desktop theme. It should be a problem for your entire panel. `~/.local/share/plasma/desktoptheme/themeName/colors`
2. I'll look into that. I guess it's a unicode issue because the other tile with 2 lines is shown properly.
3. You can Alt+Right Click to resize the menu permanently.
4. I'm unlikely to add breadcrumb navigation any time soon, sorry.

**Comment by Zren** [comment]
Also, I'm not sure why the pl translation of Info Center is causing a new line. It works fine for me. Maybe I'll try using the pl locale later. Have you found any other application that has this bug?

![](https://i.imgur.com/aIGo80B.png)

**Comment by omega3** [comment]
With English locale indeed it looks better. It is not an important issue, just a visual glitch, that's why I report. Perhaps bigger tiles with coded a pixel or a view pixels of space that separate text from the lower edge of tile and a view pixels that separate text from icon would solve the problem? Looking at your screenshot I notice that on Chromium tile text covers icon a little. 

Referring to my point 4, how about separate project that would add tiles to kicker menu
https://github.com/lxde/lxqt/issues/404
I imagine instead of this vertical panel with favourite shortcut in kicker - tiles and on the right a tree view. Just an idea. :) 
I love this idea of tiles, especially because I can put icons in order of my preference and they are big and very well visible but I am not in favour of the list as a menu. I prefer tree view.

**Comment by Zren** [comment]
> I notice that on Chromium tile text covers icon a little.

There's an outline around the text, so it's readable. I won't resize the tiles since it's the same size as windows 10. You can now edit the text in tile (right click > edit tile) if the overlapping text bothers you.
