### ISSUE TITLE
Command Output: Error on Kubuntu 16.04

### ISSUE THREAD

**Issue by lipido** [Zren/plasma-applets#68]
By downloading the applet via the "Get new widgets", I cannot launch it. The following error appears:
"Error loading QML file: file:///home/lipido/.local/share/plasma/plasmoids/com.github.zren.commandoutput/contents/ui/main.qml:2:1: module "QtQuick.Layouts" version 1.3 is not installed"

If I touch the main.qml and change 1.3 to 1.2 or 1.1, the error disappears, but the widget does not show anything (however, I can enter the options).

**Comment by Zren** [comment]
What version of Qt do you have? Are you using the Kubuntu Backports or are you still using the default Plasma 5.5 desktop? App Launcher > Info Center should display it.

**Comment by lipido** [comment]
I'm using the default:
KDE Plasma Version: 5.5.5
Qt Version: 5.5.1

I will then try the backports...

**Comment by Zren** [comment]
Yeah dont install the backports to try and fix it,  i just need to know the test environment to reproduce the bug. Though you should consider kde neon which is basically 16.04 but with updated plasma and qt, though it gets its own bugs from time to time so meh. 

Ill download the kubuntu iso and try it in a vm. Also this isnt the same widget kde 4 had...  Ill check that out too.

**Comment by lipido** [comment]
Ok, Thank you. During these days I found argos (gnome) and bitbar (osx) which is an amazing idea, so I have implemented this new plasmoid which now works for me in this version: https://github.com/lipido/kargos

**Comment by Zren** [comment]
Awesome, nice to see someone expanding on this widget. Sorry I forgot to look into this faster.

After testing with the kubuntu 16.04 iso, it seems it only supports `QtQuick.Layouts 1.2` or lower. You need to restart `plasmashell` with `killall plasmashell; kstart5 plasmashell` for changes to take effect.
