### ISSUE TITLE
[eventcalendar] Google Calendar error

### ISSUE THREAD

**Issue by lm789632** [Zren/plasma-applets#74]
openSUSE Tumbleweed
plasma5 5.9.4
org.kde.plasma.eventcalendar v43,Google Calendar show: 
Error : Could not load : file:///home/user/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/config/ConfigGoogleCalendar.qml:15 Type GoogleCalendarSession unavailable
file:///home/user/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/config/GoogleCalendarSession.qml:31 ConfigSerializedString is not a type
How to fix it?

**Comment by lm789632** [comment]
sorry,reinstall and fix.

**Comment by Zren** [comment]
Shit, I forgot to commit that file. It's in the plasmoid download from the store, but package managers might download from GitHub. Thanks for catching that.

**Comment by Zren** [comment]
Fixed in v44
