### ISSUE TITLE
[TiledMenu] Installing this in Linux Mint KDE (Plasma 5.8.5)

### ISSUE THREAD

**Issue by tjw0lf** [Zren/plasma-applets#77]
I get an error. please help i want this awesome menu

**Comment by Zren** [comment]
Open System info,  what version of plasma?

**Comment by tjw0lf** [comment]
plasma version 5.8.5

**Comment by tjw0lf** [comment]
http://www.imagebam.com/image/fefe5b544845717

**Comment by Zren** [comment]
What's the error? And which version of the widget did you install?

```
 kreadconfig5 --file ~/.local/share/plasma/plasmoids/com.github.zren.tiledmenu/metadata.desktop --group "Desktop Entry" --key "X-KDE-PluginInfo-Version"
```
Version 13 is not compatible with Plasma 5.8, you need version 11.

![](https://i.imgur.com/u0qtrdH.png)

**Comment by tjw0lf** [comment]
Well i installed 5.9. then i installed 5.6 and same thing happens getting error.

Error loading QML file: file:///home/tj/.local/share/plasma/plasmoids/com.github.zren.tiledmenu/contents/ui/Main.qml:22:2: Type AppsModel unavailable
file:///home/tj/.local/share/plasma/plasmoids/com.github.zren.tiledmenu/contents/ui/AppsModel.qml:39:3: Cannot assign to non-existent property "autoPopulate"

**Comment by Zren** [comment]
You need to restart plasma if installed the wrong one, plasma won't load the new one until plasma restarts (log out then back in).

**Comment by tjw0lf** [comment]
yaaahoooo Thank you. Your Awesome and Great Job. one thing that bugs me when you open up Tiled Menu up above the Dolphin icon it doesn't show an icon for that one its just huck of white. If you can fix it that would be awesome. Thank you

**Comment by Zren** [comment]
What Desktop Theme and Icon Theme are you using?

**Comment by tjw0lf** [comment]
Desktop theme is MX theme. Icons are default Breeze

**Comment by Zren** [comment]
Is it your user's avatar? Does clicking the button look like this?

![](https://i.imgur.com/utYCTEc.png)

**Comment by tjw0lf** [comment]
yeah that's it i don't even have that on there. Also how did you get all of those other stuff in there. Music video pictures and so on

**Comment by Zren** [comment]
It's from v13 (plasma 5.9), and those shortcuts aren't customizable yet anywho.

**Comment by tjw0lf** [comment]
Can you tell me how you got those please?  I had v13 on noen before it was the same. I want mine to look like that. If you can tell me the steps please

**Comment by tjw0lf** [comment]
those shortcuts aren't customizable yet anywho.!!!! 

So how did you get those on yours please tell me.

**Comment by Zren** [comment]
... They're in version 13, which requires Plasma 5.9.x. You probably installed v11 when you tested in KDE Neon first like you did just now.

**Comment by tjw0lf** [comment]
Can you tell me how you got them. Like that please..... Neon has v13 i don't see them

**Comment by Zren** [comment]
Logout and back in. What version is it?

**Comment by tjw0lf** [comment]
![68747470733a2f2f692e696d6775722e636f6d2f757459435445632e706e67](https://cloud.githubusercontent.com/assets/16531121/25322018/fcaf088c-2880-11e7-9ad2-9270d94022ea.png)

I want those icons on the bar...(YOU SHOWED) How did you get them

**Comment by Zren** [comment]
1. Confirm you're running Plasma 5.9
2. Delete `~/.local/share/plasma/plasmoids/com.github.zren.tiledmenu/`
3. Reinstall tiledmenu-13-plasma5.9
4. Logout
5. Log back in
6. Open the menu
