### ISSUE TITLE
Highlight color should be selectable

### ISSUE THREAD

**Issue by frispete** [Zren/plasma-applets#80]
The highlight color for current day in agenda and the weather symbol should be configurable.

**Comment by Zren** [comment]
So, I also need to set the rain fill color + mockup the color picker in the config.

![](https://i.imgur.com/mwLhBOi.png)

Any other colors you think?

**Comment by frispete** [comment]
Any idea, where the highlight color of the selected day in calendar originate from?

**Comment by Zren** [comment]
It's also based on the highlight color, but it's more of a tint on top of the text color. Basically there's a solid fill of "text color" for the current date, with a semi-transparent fill of highlight color. when it's selected. I guess I could add 3 more colors (today, selected, today+selected).

**Comment by Zren** [comment]
Bleh, never got around to actually adding the user friendly color pickers. You can edit the colors in v47 by turning on the debugging mode and going to the advanced tab (if you're comfortable with hex colors).

**Comment by Zren** [comment]
Added user friendly color pickers to v48.
