### ISSUE TITLE
[TiledMenu] Panel icon doesn't respect size

### ISSUE THREAD

**Issue by Zren** [Zren/plasma-applets#85]
https://store.kde.org/p/1160672/

> goshobul: started with that. Still 22/24 in size. My other icons are 32. Using 5.9 on manjaro if it matters

* Fixed Size is unchecked

Could Manjaro be using the 5.10 beta sources already? There was mention of panel icon sizes. Todo: test the neon dev iso.

> plasma-workspace 5.9.5, plasma-framework 5.33.0

**Comment by giomatfois62** [comment]
I'm experiencing it too, Kde Neon user edition, Plasma 5.10.3, Framework 5.34 Qt 5.9
