### ISSUE TITLE
[EventCalendar] Error loading QML file

### ISSUE THREAD

**Issue by tpnx** [Zren/plasma-applets#90]
Hello,

I am using KDE neon 5.10.2 and installed this widget from the store. When I add it, i'll get this error message:

> Error loading QML file: file:///home/<USER>/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/main.qml:96:40: Type PopupView unavailable
> file:///home/<USER>/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/PopupView.qml:322:13: Type TimerView unavailable
> file:///home/<USER>/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/TimerView.qml:5:1: plugin cannot be loaded for module "QtMultimedia": The plugin '/usr/lib/x86_64-linux-gnu/qt5/qml/QtMultimedia/libdeclarative_multimedia.so' uses incompatible Qt library. (5.9.0) [release]

Edit: Its the Event Calendar Widget

Regards
tpnx

**Comment by Zren** [comment]
Have you restarted since updating to qt 5.9?

**Comment by codewiz** [comment]
I'm seeing the same error message with Event Calendar v65 on Arch Linux (plasma-desktop 5.17.3 and Qt 5.14.0beta3):

```
Error loading QML file: file:///home/bernie/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/main.qml:100:37: Type PopupView unavailable
file:///home/bernie/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/PopupView.qml:337:4: Type AgendaView unavailable
file:///home/bernie/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/AgendaView.qml:71:15: Type AgendaListItem unavailable
file:///home/bernie/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/AgendaListItem.qml:194:15: Type AgendaEventItem unavailable
file:///home/bernie/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/AgendaEventItem.qml:253:4: Type EditEventForm unavailable
file:///home/bernie/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/EditEventForm.qml:85:5: Type DurationSelector unavailable
file:///home/bernie/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/DurationSelector.qml:24:2: Type DateTimeSelector unavailable
file:///home/bernie/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/DateTimeSelector.qml:27:2: Type DateSelector unavailable
file:///home/bernie/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/DateSelector.qml:63:33: Cannot assign object of type "T.Popup" to property of type "Popup_QMLTYPE_1074*" as the former is neither the same as the latter nor a sub-class of it.
```

**Comment by jbermejo22** [comment]
I'm seeing the same error message with Event Calendar v65 on Arco Linux ( plasma-desktop 5.0.11)
Error al cargar archivo QML: file:///home/jose3/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/main.qml:100:37: Type PopupView unavailable
file:///home/jose3/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/PopupView.qml:337:4: Type AgendaView unavailable
file:///home/jose3/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/AgendaView.qml:71:15: Type AgendaListItem unavailable
file:///home/jose3/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/AgendaListItem.qml:194:15: Type AgendaEventItem unavailable
file:///home/jose3/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/AgendaEventItem.qml:253:4: Type EditEventForm unavailable
file:///home/jose3/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/EditEventForm.qml:85:5: Type DurationSelector unavailable
file:///home/jose3/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/DurationSelector.qml:24:2: Type DateTimeSelector unavailable
file:///home/jose3/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/DateTimeSelector.qml:27:2: Type DateSelector unavailable
file:///home/jose3/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/DateSelector.qml:63:33: Cannot assign object of type "T.Popup" to property of type "Popup_QMLTYPE_411*" as the former is neither the same as the latter nor a sub-class of it.

**Comment by Zren** [comment]
@codewiz and @jbermejo22 issues are part of this bug report, and were fixed in v66 which is on AUR.

https://github.com/Zren/plasma-applet-eventcalendar/issues/99

As for the original issue, it looks like @tpnx had packages from multiple versions of qt installed or something. I assume it's fixed as Qt 5.9 was a while ago.

**Comment by backit** [comment]
I have the same issue, installed following your instructions via kde till point 4. Added as desktop object and got same issue. Cannot find point 5
kubuntu 18.04
kde 5.44

**Comment by Zren** [comment]
@backit See https://github.com/Zren/plasma-applet-eventcalendar/issues/153#issuecomment-730508702 for instructions on how to install v68 in Kubuntu 18.04.

I forget if I removed most QtMultimedia stuff by v68. The latest version of Event Calendar (v73) definitely doesn't as I migrated all the sound effect code to a python3 script that calls `libcanberra.so` directly.
