### ISSUE TITLE
[todolist] Where are saved the notes list?

### ISSUE THREAD

**Issue by vmorenomarin** [Zren/plasma-applets#91]
I want reinstall my system but I do not want lose the list notes in the widget. How could do a backup of them?
Thanks.

**Comment by Zren** [comment]
`~/.local/share/plasma_notes/todolist` (you can open it via the context menu)

**Comment by Zren** [comment]
You should also backup `~/.local/share/` and `~/.config`

**Comment by vmorenomarin** [comment]
Thanks a lot!!
