### ISSUE TITLE
[BatteryTime] Unable to change "remaining time" style

### ISSUE THREAD

**Issue by moreD** [Zren/plasma-applets#98]
Hi,

In BatteryTime widget I cannot choose the display style of time left. In the widget settings, there is an option but remains in gray all the time! I checked the code and found that it is hard-coded to display in minutes by setting an if condition to be always true. Is there any plan to remove this function or it can be fixed quickly?

Thanks!

**Comment by Zren** [comment]
Totally forgot about that. Added the switch to v4.
